### ISSUE TITLE
Installation of OHW fails due to matplotlib version

### ISSUE THREAD

**Issue by maurerjennifer** [loslab/ohw#11]
Hi there,
I was trying to get OHW running  as described in the UserGuide. Unfortunatelly I receive the following error message:

`FileNotFoundError: No such file or directory: 'C:\\Users\\[...]\\.matplotlib\\fontlist-v300.json'`

Running on Win10 with Anaconda3-2021.11. 
I found the following [issue](https://github.com/matplotlib/matplotlib/issues/12173/) related to matplotlib's version 3.0.0 on windows, which recommmends updating to a more recent version like 3.0.2. 

This unfortunatelly depends on a newer version of python (> 3.5). While also updating python, I run into further issues of non-matching dependencie versions. Regardeless I think a update to a recent python version would be appropiate, as version 3.5.6 is at its end of life since September 2020.  [^1]

Could you please have a look?

 [^1]: https://github.com/python/devguide/pull/609

**Comment by ilorevilo** [comment]
Thanks for the feedback! I updated the `OHW.yml`, it is now based on Python 3.8.

I will close this issue as we managed to get it running on your machine 🙂
